### ISSUE TITLE
Package has been renamed to pyproject-metadata

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pep621-feedstock#5]
See https://github.com/FFY00/python-pyproject-metadata/issues/10

Some questions arise:
* where to build?
  * just change the name here?
  * create a new feedstock and archive this one?
* keep compatibility wrapper for `pep621`?
  * yes
    * -> multi-output recipe
    * upstream didn't do that
    * keep for how long? indefinitely?
  * no
    * -> all consumers need to be changed (though there aren't that [many](https://github.com/search?q=org%3Aconda-forge+pep621&type=code))

**Comment by gforsyth** [comment]
Let's just change the name here and drop compatibility.  It's an alpha versioned project and I maintain most of the downstream feedstocks.

Thanks for flagging the name change!

**Comment by gforsyth** [comment]
nm, I've been advised to submit a new feedstock.  I'll be archiving this shortly.
